export const SEARCH_ACTIONS = {
	ON_SEARCH_CHANGE: 'ON_SEARCH_CHANGE',
	FETCH_SEARCH_REQUEST: 'FETCH_SEARCH_REQUEST',
	FETCH_SEARCH_FULFILLED: 'FETCH_SEARCH_FULFILLED',
	CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS',
};
